# I have no idea what this is for

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/status || exit 1"]

  frontend:
    build:
      no_cache: true
    environment:
      - API_URL=${API_URL}
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  website:
    build:
      no_cache: true
    environment:
      - WATCHPACK_POLLING=true

# This program has been developed by students from the bachelor Computer Science at Utrecht
# University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)