x-target: &target
  target: ${TARGET:-development} # If TARGET is not set, default to development

# TODO: check if this works
x-API_URL: &API_URL
  API_URL=${API_URL:-http://backend:8080} # If API_URL is not set, guess

services:
  # Start database
  database:
    image: postgres:latest
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Start storage
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - ${STORAGE_PORT:-10000}:10000
    restart: unless-stopped

  # Start backend with database and storage
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - ${BACKEND_PORT:-8080}:8080
    environment:
      HOST_URL: ${FROTEND_DOMAIN:-http://localhost:${FRONTEND_PORT:-3000}} # Public URL for the email
      DATABASE_CONNECTION_STRING: >-
        Host=database;
        Port=5432;
        Username=${DATABASE_USER:-postgres};
        Password=${DATABASE_PASSWORD:?Database password is required};
        Database=${DATABASE_NAME:-postgres};
        Include Error Detail=true
      # Spaces aren't allowed so use \ with "" which is the only multiline syntax to have nothing between lines
      STORAGE_CONNECTION_STRING: # TODO: Use a real connection string
        "DefaultEndpointsProtocol=http;\
        AccountName=devstoreaccount1;\
        AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;\
        BlobEndpoint=http://storage:10000/devstoreaccount1;"
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:?Emall SMTP host is required}
      EMAIL_TLS_PORT:  ${EMAIL_TLS_PORT:-587}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS:?Email address is required}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:?Email password is required}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-$EMAIL_ADDRESS}
      OwnerUser__Email: ${OwnerUser__Email:?OwnerUser email is required}
      OwnerUser__Password: ${OwnerUser__Password:?OwnerUser password is required}
      OwnerUser__FirstName: ${OwnerUser__FirstName:-Owner}
      OwnerUser__LastName: ${OwnerUser__LastName:-Owner}
    depends_on:
      database:
        condition: service_healthy
      storage:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 150s
    restart: unless-stopped

  # Start frontend after backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    environment:
      - API_URL=${API_URL:-http://backend:8080} # Do NOT use the global port here
      - HELP_URL=${HELP_URL:-http://localhost:${WEBSITE_PORT:-3001}}
      - NEXT_PUBLIC_TIMEZONE=${NEXT_PUBLIC_TIMEZONE:-UTC}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  # Start website after backend
  # website:
  #   build:
  #     context: ./website
  #     dockerfile: Dockerfile
  #     <<: *target
  #   ports:
  #     - ${WEBSITE_PORT:-3001}:3001
  #   environment:
  #     - API_URL=${API_URL:-http://backend:8080} # Do NOT use the global port here
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   restart: unless-stopped

# This program has been developed by students from the bachelor Computer Science at Utrecht
# University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)