# Add automatic restarts and logging to all services
x-productionbase: &productionbase
  restart: unless-stopped
  logging:
    driver: "local"
    options:
      max-size: "10m"
      max-file: "5"

services:
  database:
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume
    <<: *productionbase

  storage:
    volumes:
      - storage_data:/data  # Persistent volume
    <<: *productionbase

  backend:
    healthcheck: # Slightly modify health check
      timeout: 5s
      retries: 3
      start_period: 30s
    <<: *productionbase

  frontend:
    <<: *productionbase
  
  website:
    <<: *productionbase

volumes:
  postgres_data:  # Persistent volume for database
  storage_data:   # Persistent volume for storage

# This program has been developed by students from the bachelor Computer Science at Utrecht
# University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)