networks:
  dev_network:
    name: dev_network
    driver: bridge

x-network: &network
  networks:
    - dev_network

# Target to use for building the images
x-target: &target
  target: development

# For the java script end, we have to turn on WATCHPACK_POLLING and turn of the cache,
# otherwise hot reload does not work on windows
# Base args for the js code bases
x-jsbase: &jsbase
  build:
    <<: *target
    no_cache: true
  environment:
    - WATCHPACK_POLLING=true
  <<: *network

services:
  # Set up temporary folders for storages
  database:
    tmpfs:
      - /var/lib/postgresql/data
    <<: *network

  storage:
    tmpfs:
      - /data
    <<: *network

  # For our dev environment we need to extend all coded services with volumes for hot reload
  backend:
    build:
      <<: *target
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true # Also restart for outside changes
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
      - ./testdata:/app/testdata
    command: dotnet watch --project backend.csproj run --urls http://+:${PORT:-8080} # Use dotnet watch for hot reload, PORT is set in the dockerfile
    <<: *network
  
  frontend:
    <<: *jsbase
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
  
  website:
    <<: *jsbase
    volumes:
      - ./website:/app
      - /app/node_modules
      - /app/.next

# This program has been developed by students from the bachelor Computer Science at Utrecht
# University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)