networks:
  ci_network:
    name: ci_network
    driver: bridge

x-network: &network
  networks:
    - ci_network

# Target to use for building the images
x-target: &target
  target: ci-runner

# Base args for the js code bases
x-jsbase: &jsbase
  build:
    <<: *target
  environment:
    - NODE_ENV=${NODE_ENV:-production}
  <<: *network

services:
  # Set up temporary folders for storages
  database:
    tmpfs:
      - /var/lib/postgresql/data
    <<: *network

  storage:
    tmpfs:
      - /data
    <<: *network

  # Uncertain what these are for, but these were differences from prod compose
  backend:
    build:
      <<: *target
      context: .
      dockerfile: ./backend/Dockerfile
    <<: *network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/status || exit 1"]

  frontend:
    <<: *jsbase

  # website:
  #   <<: *jsbase

# This program has been developed by students from the bachelor Computer Science at Utrecht
# University within the Software Project course.
# © Copyright Utrecht University (Department of Information and Computing Sciences)