x-target: &target
  target: ${TARGET:-development} # If TARGET is not set, default to development

networks:
  my_network:
    name: my_network
    driver: bridge

services:
  # Start database
  database:
    image: postgres:latest
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Start storage
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - ${STORAGE_PORT:-10000}:10000
    tmpfs:
      - /data
    networks:
      - my_network

  # Start backend with database and storage
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - 8090:8090
      - ${BACKEND_PORT:-8080}:8080
    environment:
      FRONTEND_DOMAIN: http://localhost:${FRONTEND_PORT:-3000} # Public URL for the email
      DATABASE_CONNECTION_STRING: >-
        Host=database;
        Port=5432;
        Username=${DATABASE_USER:-postgres};
        Password=${DATABASE_PASSWORD:?};
        Database=${DATABASE_NAME:-postgres};
        Include Error Detail=true
      # Spaces aren't allowed so use \ with ""
      STORAGE_CONNECTION_STRING:
        "DefaultEndpointsProtocol=http;\
        AccountName=devstoreaccount1;\
        AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;\
        BlobEndpoint=http://storage:10000/devstoreaccount1;"
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:?}
      EMAIL_TLS_PORT:  ${EMAIL_TLS_PORT:-587}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS:?}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:?}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-$EMAIL_ADDRESS}
    depends_on:
      database:
        condition: service_healthy
      storage:
        condition: service_started
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 150s

  # Start frontend after backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    environment:
      - WEBSITE_DOMAIN=http://localhost:${WEBSITE_PORT:-3001}
      - API_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - my_network

  # Start website after backend
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
      <<: *target
    ports:
      - ${WEBSITE_PORT:-3001}:3001
    environment:
      - API_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - my_network