x-target: &target
  target: ${TARGET:-development} # If TARGET is not set, default to development

x-API_URL: &API_URL
  API_URL=${API_URL:-http://backend:8080} # If API_URL is not set, guess

services:
  # Start database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Start storage
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"

  # Start backend with database and storage
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=Host=database;Port=5432;Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-postgres};Database=${DB_NAME:-postgres};Include Error Detail=true
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;
      - HOST_URL=${HOST_URL}
    depends_on:
      database:
        condition: service_healthy
      storage:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 150s

  # Start frontend after backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      <<: *target
    ports:
      - "3000:3000"
    environment:
      - *API_URL
      - NEXT_PUBLIC_TIMEZONE=${NEXT_PUBLIC_TIMEZONE}
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy

  # Start website after backend
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
      <<: *target
    ports:
      - "3001:3001"
    environment:
      - *API_URL
    depends_on:
      backend:
        condition: service_healthy