// <auto-generated />
using System;
using KnowledgeBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace KnowledgeBank.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260515113344_AddProjectIdToChats")]
    partial class AddProjectIdToChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeBank.Models.AudioMetadata", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("length");

                    b.HasKey("ResourceId");

                    b.ToTable("audio-metadata");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ChangelogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("changelog");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Chats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation-date");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project-id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user-id");

                    b.HasKey("Id");

                    b.ToTable("chats");
                });

            modelBuilder.Entity("KnowledgeBank.Models.DocumentMetadata", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.HasKey("ResourceId");

                    b.ToTable("document-metadata");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation-date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email-address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("TrashDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trash-date");

                    b.Property<bool>("Trashed")
                        .HasColumnType("boolean")
                        .HasColumnName("trashed");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("entities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("KnowledgeBank.Models.EntityChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkPart")
                        .HasColumnType("integer")
                        .HasColumnName("chunk-part");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk-text");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk-type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created-at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity-id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("idx_entity_chunks_entity_id");

                    b.ToTable("entity-chunks");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("invitations");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("journals");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Messages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat-id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation-date");

                    b.Property<string>("MessageRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message-role");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("KnowledgeBank.Models.OrganisationRelationship", b =>
                {
                    b.Property<Guid>("SourceOrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source-organisation-id");

                    b.Property<Guid>("TargetOrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("target-organisation-id");

                    b.Property<string>("Relation")
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.HasKey("SourceOrganisationId", "TargetOrganisationId");

                    b.HasIndex("TargetOrganisationId");

                    b.ToTable("organisation-relationships");
                });

            modelBuilder.Entity("KnowledgeBank.Models.PersonOrganisationRelation", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person-id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation-id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("PersonId", "OrganisationId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("person-organisation");
                });

            modelBuilder.Entity("KnowledgeBank.Models.PersonRelationship", b =>
                {
                    b.Property<Guid>("SourcePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("source-person-id");

                    b.Property<Guid>("TargetPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("target-person-id");

                    b.Property<string>("Relation")
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.HasKey("SourcePersonId", "TargetPersonId");

                    b.HasIndex("TargetPersonId");

                    b.ToTable("person-person");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation-date");

                    b.Property<DateTime>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion-date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("project-type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectCreatorRelation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project-id");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text")
                        .HasColumnName("creator-id");

                    b.HasKey("ProjectId", "CreatorId");

                    b.HasIndex("CreatorId");

                    b.ToTable("project-creator");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectFolderRelation", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent-id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child-id");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added-by");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("project-folder");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectItemRelation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project-id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item-id");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text")
                        .HasColumnName("added-by");

                    b.HasKey("ProjectId", "ItemId");

                    b.ToTable("project-item");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectTagRelation", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project-id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag-id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added-by");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("project-tag");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("regions");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiGeneratedTags")
                        .HasColumnType("text")
                        .HasColumnName("ai-generated-tags");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation-date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileExt")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("file-ext");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("filetype");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal-id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language-code");

                    b.Property<string>("License")
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PublicationCode")
                        .HasColumnType("text")
                        .HasColumnName("publication-code");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication-date");

                    b.Property<int?>("PublicationDatePrecision")
                        .HasColumnType("integer")
                        .HasColumnName("publication-date-precision");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source-url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("TrashDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trash-date");

                    b.Property<bool>("Trashed")
                        .HasColumnType("boolean")
                        .HasColumnName("trashed");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type-id");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("TypeId");

                    b.ToTable("resources");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceAuthorRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author-id");

                    b.HasKey("ResourceId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("resource-author");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkPart")
                        .HasColumnType("integer")
                        .HasColumnName("chunk-part");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk-text");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk-type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created-at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("idx_resource_chunks_resource_id");

                    b.HasIndex("ResourceId", "ChunkPart")
                        .HasDatabaseName("id_resource_chunks_resource_part");

                    b.ToTable("resource-chunks");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceGridItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("JournalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublicationDatePrecision")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("resourcegridview", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceGridSearchResult", b =>
                {
                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublicationDatePrecision")
                        .HasColumnType("integer");

                    b.Property<float>("Relevance")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceOrganisationRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation-id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("ResourceId", "OrganisationId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("resource-organisation");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceRegionRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region-id");

                    b.HasKey("ResourceId", "RegionId");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("idx_resource_region_region_id");

                    b.ToTable("resource-region");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceRelatedPersonRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person-id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("ResourceId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("resource-related_person");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceSourceRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("ResourceId", "Url");

                    b.ToTable("resource-source");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceTagRelation", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag-id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added-by");

                    b.HasKey("ResourceId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("idx_resource_tag_tag_id");

                    b.ToTable("resource-tag");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceTrashItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TrashDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("resourcetrashview", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("resource-types");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved-by");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved-on");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created-by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created-on");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is-approved");

                    b.Property<bool>("IsStandardized")
                        .HasColumnType("boolean")
                        .HasColumnName("is-standardized");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("KnowledgeBank.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("CustomAvatarVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LastSeenChangelogId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.VideoMetadata", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("length");

                    b.HasKey("ResourceId");

                    b.ToTable("video-metadata");
                });

            modelBuilder.Entity("KnowledgeBank.Models.WebsiteMetadata", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource-id");

                    b.Property<DateTime?>("AccessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed-on");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("ResourceId");

                    b.ToTable("website-metadata");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.Organisation", b =>
                {
                    b.HasBaseType("KnowledgeBank.Models.Entity");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.Person", b =>
                {
                    b.HasBaseType("KnowledgeBank.Models.Entity");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text")
                        .HasColumnName("linkedin");

                    b.Property<string>("Occupation")
                        .HasColumnType("text")
                        .HasColumnName("occupation");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("KnowledgeBank.Models.AudioMetadata", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithOne("AudioMetadata")
                        .HasForeignKey("KnowledgeBank.Models.AudioMetadata", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.DocumentMetadata", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithOne("DocumentMetadata")
                        .HasForeignKey("KnowledgeBank.Models.DocumentMetadata", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.EntityChunk", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Messages", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Chats", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("KnowledgeBank.Models.OrganisationRelationship", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Organisation", "SourceOrganisation")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("SourceOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Organisation", "TargetOrganisation")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("TargetOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceOrganisation");

                    b.Navigation("TargetOrganisation");
                });

            modelBuilder.Entity("KnowledgeBank.Models.PersonOrganisationRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Organisation", "Organisation")
                        .WithMany("PersonOrganisationRelations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Person", "Person")
                        .WithMany("PersonOrganisationRelations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KnowledgeBank.Models.PersonRelationship", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Person", "SourcePerson")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("SourcePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Person", "TargetPerson")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("TargetPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourcePerson");

                    b.Navigation("TargetPerson");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectCreatorRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Project", "Project")
                        .WithMany("ProjectCreatorRelations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectFolderRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Project", "ChildFolder")
                        .WithMany("ParentFolders")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Project", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFolder");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectItemRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Project", "Project")
                        .WithMany("ProjectItemRelations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ProjectTagRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Project", "Project")
                        .WithMany("ProjectTagRelations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Resource", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Journal", "Journal")
                        .WithMany("Resources")
                        .HasForeignKey("JournalId");

                    b.HasOne("KnowledgeBank.Models.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceAuthorRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Entity", "Author")
                        .WithMany("ResourceAuthorRelations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany("ResourceAuthorRelations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceChunk", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceOrganisationRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Organisation", "Organisation")
                        .WithMany("ResourceOrganisationRelations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany("ResourceOrganisationRelations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceRegionRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Region", "Region")
                        .WithMany("ResourceRegionRelations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany("ResourceRegionRelations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceRelatedPersonRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Person", "Person")
                        .WithMany("ResourceRelatedPersonRelations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany("ResourceRelatedPersonRelations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceSourceRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceTagRelation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithMany("ResourceTagRelations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.Tag", "Tag")
                        .WithMany("ResourceTagRelations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KnowledgeBank.Models.VideoMetadata", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithOne("VideoMetadata")
                        .HasForeignKey("KnowledgeBank.Models.VideoMetadata", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("KnowledgeBank.Models.WebsiteMetadata", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Resource", "Resource")
                        .WithOne("WebsiteMetadata")
                        .HasForeignKey("KnowledgeBank.Models.WebsiteMetadata", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KnowledgeBank.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KnowledgeBank.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBank.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KnowledgeBank.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBank.Models.Organisation", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Entity", null)
                        .WithOne()
                        .HasForeignKey("KnowledgeBank.Models.Organisation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBank.Models.Person", b =>
                {
                    b.HasOne("KnowledgeBank.Models.Entity", null)
                        .WithOne()
                        .HasForeignKey("KnowledgeBank.Models.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBank.Models.Chats", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Entity", b =>
                {
                    b.Navigation("ResourceAuthorRelations");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Journal", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Project", b =>
                {
                    b.Navigation("ChildFolders");

                    b.Navigation("ParentFolders");

                    b.Navigation("ProjectCreatorRelations");

                    b.Navigation("ProjectItemRelations");

                    b.Navigation("ProjectTagRelations");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Region", b =>
                {
                    b.Navigation("ResourceRegionRelations");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Resource", b =>
                {
                    b.Navigation("AudioMetadata");

                    b.Navigation("DocumentMetadata");

                    b.Navigation("ResourceAuthorRelations");

                    b.Navigation("ResourceOrganisationRelations");

                    b.Navigation("ResourceRegionRelations");

                    b.Navigation("ResourceRelatedPersonRelations");

                    b.Navigation("ResourceTagRelations");

                    b.Navigation("VideoMetadata");

                    b.Navigation("WebsiteMetadata");
                });

            modelBuilder.Entity("KnowledgeBank.Models.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Tag", b =>
                {
                    b.Navigation("ResourceTagRelations");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Organisation", b =>
                {
                    b.Navigation("PersonOrganisationRelations");

                    b.Navigation("ResourceOrganisationRelations");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("KnowledgeBank.Models.Person", b =>
                {
                    b.Navigation("PersonOrganisationRelations");

                    b.Navigation("ResourceRelatedPersonRelations");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
