type Greeting = {
    heading: string;
    subtext: string;
};

type GreetingTemplate = {
    heading: (name: string) => string;
    subtext: string;
};

const morning: GreetingTemplate[] = [
    { heading: n => `Good morning, ${n}!`, subtext: "Ready to tackle the day?" },
    { heading: n => `Rise and shine, ${n}!`, subtext: "Let's get things done." },
    { heading: n => `Morning, ${n}!`, subtext: "Coffee's brewing, time to get started." },
    { heading: n => `Good morning, ${n}!`, subtext: "A fresh day, a fresh start." },
    { heading: n => `Hey ${n}, good morning!`, subtext: "What are we diving into today?" },
    { heading: n => `Morning, ${n}!`, subtext: "The early bird catches the worm." },
    { heading: n => `Good morning, ${n}!`, subtext: "Let's make today count." },
    { heading: n => `Hey, good morning ${n}!`, subtext: "Hope you slept well." },
    { heading: n => `Good morning, ${n}!`, subtext: "A new day, new possibilities." },
    { heading: n => `Morning, ${n}!`, subtext: "Ready to get to work?" },
    { heading: n => `Wakey wakey, ${n}!`, subtext: "Time to do something productive." },
    { heading: n => `Good morning, ${n}!`, subtext: "The day is yours." },
    { heading: n => `Morning, ${n}!`, subtext: "Let's see what today has in store." },
    { heading: n => `Good morning, ${n}!`, subtext: "Time to make some progress." },
    { heading: n => `Hey ${n}! Morning!`, subtext: "Where do you want to start?" },
    { heading: n => `Morning, ${n}!`, subtext: "First coffee or straight to work?" },
    { heading: n => `Good morning, ${n}!`, subtext: "Another day, another chance." },
    { heading: n => `Hey ${n}, morning!`, subtext: "Lots to do today?" },
    { heading: n => `Morning, ${n}!`, subtext: "Let's have a good one." },
    { heading: n => `Good morning, ${n}!`, subtext: "Hope the coffee is strong." },
    { heading: n => `Morning, ${n}!`, subtext: "The day is just getting started." },
    { heading: n => `Good morning, ${n}!`, subtext: "Make it a good one." },
    { heading: n => `Morning, ${n}!`, subtext: "Time to get after it." },
    { heading: n => `Good morning, ${n}!`, subtext: "What's first on the list?" },
    { heading: n => `Hey ${n}, good morning!`, subtext: "Let's get moving." },
    { heading: n => `Morning, ${n}!`, subtext: "Bright and early, good on you." },
    { heading: n => `Good morning, ${n}!`, subtext: "Today's a good day to be productive." },
    { heading: n => `Morning, ${n}!`, subtext: "Off to a good start?" },
    { heading: n => `Hey ${n}!`, subtext: "Morning! What's the plan?" },
    { heading: n => `Good morning, ${n}!`, subtext: "The world is quiet, get stuff done." },
    { heading: n => `Morning, ${n}!`, subtext: "Seize the day." },
    { heading: n => `Good morning, ${n}!`, subtext: "Hope the commute was kind." },
    { heading: n => `Morning, ${n}!`, subtext: "Right on time." },
    { heading: n => `Hey ${n}, morning!`, subtext: "Sleep well?" },
    { heading: n => `Good morning, ${n}!`, subtext: "Let's go." },
    { heading: n => `Morning, ${n}!`, subtext: "Fresh start, fresh mind." },
    { heading: n => `Morning, ${n}!`, subtext: "On a roll already?" },
    { heading: n => `Good morning, ${n}!`, subtext: "Sun's up, so are you." },
    { heading: n => `Hey ${n}!`, subtext: "Welcome back. Good morning." },
    { heading: n => `Morning, ${n}!`, subtext: "One step at a time." },
    { heading: n => `Good morning, ${n}!`, subtext: "Ready when you are." },
    { heading: n => `Morning, ${n}!`, subtext: "Let's do something useful today." },
    { heading: n => `Hey ${n}, morning!`, subtext: "Early start, nice." },
    { heading: n => `Good morning, ${n}!`, subtext: "A clean slate." },
    { heading: n => `Morning, ${n}!`, subtext: "What's on the agenda?" },
    { heading: n => `Good morning, ${n}!`, subtext: "Let's hit the ground running." },
    { heading: n => `Morning, ${n}!`, subtext: "You've got this." },
    { heading: n => `Good morning, ${n}!`, subtext: "Let's make it happen." },
    { heading: n => `Morning, ${n}!`, subtext: "Good things take effort. Let's go." },
    { heading: n => `Good morning, ${n}!`, subtext: "Here we go again." },
];

const afternoon: GreetingTemplate[] = [
    { heading: n => `Good afternoon, ${n}!`, subtext: "How's the day treating you?" },
    { heading: n => `Hey ${n}!`, subtext: "Hope the morning was productive." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Keep that momentum going." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Still plenty of day left." },
    { heading: n => `Hey ${n}, afternoon!`, subtext: "What are we working on?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "The grind continues." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Let's make the most of it." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Ready for the second half?" },
    { heading: n => `Hey ${n}!`, subtext: "Afternoon already, time flies." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Let's get back to it." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Coffee number two, perhaps?" },
    { heading: n => `Hey ${n}, good afternoon!`, subtext: "What's on the agenda?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "Halfway through and still going strong." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Time to get things done." },
    { heading: n => `Hey ${n}!`, subtext: "The afternoon awaits." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Staying on track?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "Anything good for lunch?" },
    { heading: n => `Hey ${n}!`, subtext: "How's the afternoon treating you?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Still in the zone?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "Powering through?" },
    { heading: n => `Hey ${n}, afternoon!`, subtext: "Need a stretch break?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "On a roll?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "Getting things crossed off the list?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "The focus is real." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Let's keep it going." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Deep work hours." },
    { heading: n => `Hey ${n}, good afternoon!`, subtext: "Making progress?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "The day isn't over yet." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Keeping the momentum." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Almost there." },
    { heading: n => `Afternoon, ${n}!`, subtext: "What's left on the list?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Sun's still up, keep going." },
    { heading: n => `Hey ${n}, afternoon!`, subtext: "In the zone?" },
    { heading: n => `Afternoon, ${n}!`, subtext: "You've done a lot today." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Solid work so far." },
    { heading: n => `Afternoon, ${n}!`, subtext: "One thing at a time." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Things getting done?" },
    { heading: n => `Hey ${n}, afternoon!`, subtext: "Keep it up." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Good pace today." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Almost through the day." },
    { heading: n => `Hey ${n}!`, subtext: "Need a coffee refill?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Focus time." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Not long now." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "The finish line is in sight." },
    { heading: n => `Hey ${n}, afternoon!`, subtext: "Wrapping up or still going strong?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Work smarter, not harder." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Home stretch." },
    { heading: n => `Good afternoon, ${n}!`, subtext: "You've got this." },
    { heading: n => `Afternoon, ${n}!`, subtext: "Steady pace, steady progress." },
    { heading: n => `Hey ${n}!`, subtext: "Afternoon check in. How's it?" },
    { heading: n => `Good afternoon, ${n}!`, subtext: "Right, let's get on with it." },
];

const evening: GreetingTemplate[] = [
    { heading: n => `Good evening, ${n}!`, subtext: "Wrapping up or just getting started?" },
    { heading: n => `Evening, ${n}!`, subtext: "The quiet hours are upon us." },
    { heading: n => `Hey ${n}, good evening!`, subtext: "Still at it?" },
    { heading: n => `Good evening, ${n}!`, subtext: "The day's winding down. Let's make it count." },
    { heading: n => `Evening, ${n}!`, subtext: "Nothing like a productive evening." },
    { heading: n => `Good evening, ${n}!`, subtext: "Hope the day was kind to you." },
    { heading: n => `Hey ${n}!`, subtext: "Evening mode activated." },
    { heading: n => `Evening, ${n}!`, subtext: "The best ideas come after hours." },
    { heading: n => `Good evening, ${n}!`, subtext: "What are we finishing up tonight?" },
    { heading: n => `Hey ${n}, evening!`, subtext: "Squeezing in a bit more work?" },
    { heading: n => `Evening, ${n}!`, subtext: "Almost there for today." },
    { heading: n => `Good evening, ${n}!`, subtext: "A solid evening of work ahead." },
    { heading: n => `Hey ${n}!`, subtext: "Evening already, time flies." },
    { heading: n => `Evening, ${n}!`, subtext: "Let's close out the day strong." },
    { heading: n => `Good evening, ${n}!`, subtext: "Time to focus up." },
    { heading: n => `Evening, ${n}!`, subtext: "End of day energy." },
    { heading: n => `Good evening, ${n}!`, subtext: "Any wins today?" },
    { heading: n => `Hey ${n}, evening!`, subtext: "Day done or still pushing?" },
    { heading: n => `Evening, ${n}!`, subtext: "Evening hours are gold for focus." },
    { heading: n => `Hey ${n}!`, subtext: "Got a lot done today?" },
    { heading: n => `Evening, ${n}!`, subtext: "The office is quieting down." },
    { heading: n => `Good evening, ${n}!`, subtext: "Productive evening ahead?" },
    { heading: n => `Hey ${n}, good evening!`, subtext: "Last stretch of the day." },
    { heading: n => `Evening, ${n}!`, subtext: "How did today go?" },
    { heading: n => `Good evening, ${n}!`, subtext: "Getting the last bits done." },
    { heading: n => `Hey ${n}!`, subtext: "Evening mode. What's left?" },
    { heading: n => `Evening, ${n}!`, subtext: "One last push." },
    { heading: n => `Hey ${n}, evening!`, subtext: "Just you and your work now." },
    { heading: n => `Evening, ${n}!`, subtext: "The quiet hours hit different." },
    { heading: n => `Good evening, ${n}!`, subtext: "Finishing strong." },
    { heading: n => `Hey ${n}!`, subtext: "You've earned a break soon." },
    { heading: n => `Evening, ${n}!`, subtext: "Almost done for the day." },
    { heading: n => `Good evening, ${n}!`, subtext: "Few more things to knock out?" },
    { heading: n => `Hey ${n}, good evening!`, subtext: "Day's winding down nicely." },
    { heading: n => `Evening, ${n}!`, subtext: "Evening productivity is underrated." },
    { heading: n => `Good evening, ${n}!`, subtext: "Got some focus time left?" },
    { heading: n => `Evening, ${n}!`, subtext: "Home stretch." },
    { heading: n => `Good evening, ${n}!`, subtext: "The to-do list won't do itself." },
    { heading: n => `Hey ${n}, evening!`, subtext: "Productive day?" },
    { heading: n => `Evening, ${n}!`, subtext: "Making the most of the evening." },
    { heading: n => `Good evening, ${n}!`, subtext: "Calm and focused." },
    { heading: n => `Hey ${n}!`, subtext: "What are we wrapping up?" },
    { heading: n => `Evening, ${n}!`, subtext: "Getting it done before bed." },
    { heading: n => `Good evening, ${n}!`, subtext: "Clear head, good work." },
    { heading: n => `Hey ${n}, good evening!`, subtext: "Getting there." },
    { heading: n => `Evening, ${n}!`, subtext: "Steady as she goes." },
    { heading: n => `Good evening, ${n}!`, subtext: "Almost done, keep going." },
    { heading: n => `Evening, ${n}!`, subtext: "A good day deserves a good finish." },
    { heading: n => `Good evening, ${n}!`, subtext: "Right, let's get the last bits done." },
    { heading: n => `Hey ${n}, evening!`, subtext: "Still going? Good." },
    { heading: n => `Evening, ${n}!`, subtext: "What a day. Keep at it." },
];

const lateNight: GreetingTemplate[] = [
    { heading: n => `Still up, ${n}?`, subtext: "Burning the midnight oil, I see." },
    { heading: n => `Hey ${n}!`, subtext: "The night shift, huh?" },
    { heading: n => `Up late, ${n}?`, subtext: "The night owls are in their element." },
    { heading: n => `Late night, ${n}!`, subtext: "You and the stars are both working overtime." },
    { heading: n => `Hey ${n}, up late?`, subtext: "Nice and quiet, good for deep work." },
    { heading: n => `Burning the midnight oil, ${n}?`, subtext: "The dedicated ones always are." },
    { heading: n => `Late night grind, ${n}!`, subtext: "The office is yours at this hour." },
    { heading: n => `Hey ${n}!`, subtext: "Still going? Respect." },
    { heading: n => `Up late, ${n}!`, subtext: "Best time to get stuff done without interruptions." },
    { heading: n => `Night owl mode, ${n}!`, subtext: "World's quiet, make it count." },
    { heading: n => `Hey ${n}, late night?`, subtext: "Don't forget to take a break." },
    { heading: n => `Still at it, ${n}?`, subtext: "The night shift crew never quits." },
    { heading: n => `Late night, ${n}!`, subtext: "Sometimes the best work happens after midnight." },
    { heading: n => `Hey ${n}!`, subtext: "The night is young... or is it?" },
    { heading: n => `Up late, ${n}?`, subtext: "The dedicated never rest." },
    { heading: n => `Still going, ${n}?`, subtext: "You're built different." },
    { heading: n => `Late night session, ${n}!`, subtext: "The hardest workers are up right now." },
    { heading: n => `Hey ${n}!`, subtext: "Still here? Mad respect." },
    { heading: n => `Up late, ${n}!`, subtext: "The night is productive." },
    { heading: n => `Late night, ${n}!`, subtext: "Coffee keeping you company?" },
    { heading: n => `Still at it, ${n}!`, subtext: "The late shift hits different." },
    { heading: n => `Hey ${n}!`, subtext: "Late night work is underrated." },
    { heading: n => `Up late, ${n}?`, subtext: "What are we getting done?" },
    { heading: n => `Late night grind, ${n}!`, subtext: "The world's asleep, you're not." },
    { heading: n => `Hey ${n}, late night!`, subtext: "Almost midnight and still going." },
    { heading: n => `Still going, ${n}!`, subtext: "Consistency is key." },
    { heading: n => `Hey ${n}!`, subtext: "Night shift crew represent." },
    { heading: n => `Up late, ${n}?`, subtext: "The quiet hours are yours." },
    { heading: n => `Late night, ${n}!`, subtext: "Some of the best work happens now." },
    { heading: n => `Still at it, ${n}?`, subtext: "The grind doesn't sleep." },
    { heading: n => `Hey ${n}!`, subtext: "Deep night, deep work." },
    { heading: n => `Late night session, ${n}!`, subtext: "Nobody to distract you now." },
    { heading: n => `Hey ${n}, still going?`, subtext: "The late shift suits you." },
    { heading: n => `Up late, ${n}!`, subtext: "Dedicated or just a night person?" },
    { heading: n => `Still here, ${n}?`, subtext: "You're on a roll." },
    { heading: n => `Hey ${n}!`, subtext: "Going strong." },
    { heading: n => `Late night, ${n}!`, subtext: "Whatever it takes." },
    { heading: n => `Still at it, ${n}?`, subtext: "The night owls always win." },
    { heading: n => `Up late, ${n}?`, subtext: "Classic." },
    { heading: n => `Late night, ${n}!`, subtext: "Just you and your work." },
    { heading: n => `Hey ${n}, still up?`, subtext: "Getting things done." },
    { heading: n => `Still going, ${n}?`, subtext: "The nighttime focus is real." },
    { heading: n => `Hey ${n}!`, subtext: "Late hours, big output." },
    { heading: n => `Up late, ${n}!`, subtext: "This is when it all comes together." },
    { heading: n => `Late night grind, ${n}!`, subtext: "The committed ones show up at all hours." },
    { heading: n => `Hey ${n}, up late?`, subtext: "Good time to get things done." },
    { heading: n => `Still up, ${n}?`, subtext: "The night has its own kind of energy." },
    { heading: n => `Up late, ${n}!`, subtext: "No distractions at this hour." },
    { heading: n => `Hey ${n}!`, subtext: "Working into the night. Respect." },
    { heading: n => `Late night, ${n}!`, subtext: "The quiet is yours." },
    { heading: n => `Still at it, ${n}?`, subtext: "You know what you're doing." },
];

function pickRandom<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
}

export function getGreeting(firstName: string): Greeting {
    const hour = new Date().getHours();

    let template: GreetingTemplate;
    if (hour < 12) {
        template = pickRandom(morning);
    } else if (hour < 18) {
        template = pickRandom(afternoon);
    } else if (hour < 21) {
        template = pickRandom(evening);
    } else {
        template = pickRandom(lateNight);
    }

    return {
        heading: template.heading(firstName),
        subtext: template.subtext,
    };
}
